SELECTABLE_AMENITIES = {
    'doctors': 'Doctor',
    'fuel': 'Fuel',
    'university': 'University',
    'hospital': 'Hospital',
    'bus_station': 'Public Transport Stop',
    'parking': 'Parking',
    'school': 'School',
    'marketplace': 'Marketplace',
    'police': 'Police',
    'post_office': 'Post Office',
    'dentist': 'Dentist',
    'kindergarten': 'Kindergarten',
    'pharmacy': 'Pharmacy',
    'library': 'Library',
    'bank': 'Bank',
    'charging_station': 'Charging Station',
    'atm': 'ATM',
    'fire_station': 'Fire Station',
    'restaurant': 'Restaurant',
    'cinema': 'Cinema',
    'veterinary': 'Veterinary',
    'bar': 'Bar',
}
