SELECTABLE_AMENITIES = {
    'doctors': 'Doctor',
    'fuel': 'Fuel',
    'university': 'University',
    'hospital': 'Hospital',
    'bus_station': 'Public Transport Stop',
    'parking': 'Parking',
    'school': 'School',
    'shop': 'Shop',
    'police': 'Police',
    'post_office': 'Post Office',
    'dentist': 'Dentist',
    'kindergarten': 'Kindergarten',
    'pharmacy': 'Pharmacy',
    'library': 'Library',
    'bank': 'Bank',
    'charging_station': 'Charging Station',
    'atm': 'ATM',
    'fire_station': 'Fire Station',
    'restaurant': 'Restaurant',
    'cinema': 'Cinema',
    'veterinary': 'Veterinary',
    'bar': 'Bar',
}

AMENITY_KEYS = {
    'doctors': 'doctor',
    'fuel': 'fuel',
    'university': 'college',
    'hospital': 'hospital',
    'bus_station': 'bus',
    'parking': 'car',
    'school': 'school',
    'shop': 'shop',
    'police': 'police',
    'post_office': 'post',
    'dentist': 'dentist',
    'kindergarten': 'playground',
    'pharmacy': 'pharmacy',
    'library': 'library',
    'bank': 'bank',
    'charging_station': 'station',
    'atm': 'bank',
    'fire_station': 'fire-station',
    'restaurant': 'restaurant',
    'cinema': 'cinema',
    'veterinary': 'veterinary',
    'bar': 'bar',
}
